### ISSUE TITLE
UART is ATmega2560 specific

### ISSUE THREAD

**Issue by darrylring** [UVicFormulaMotorsports/CANmon#1]
The UART code is currently specific to the ATmega2560 (the MCU on an Arduino Mega 2560), not the ATmega16M1 on this board. The UART on the ATmega16M1 is actually combined with a LIN controller, and the registers are completely different. Only the register and bit names *should* need changing, and only `src/cm_uart.c` will be affected.

## Tasks

- [ ] Map the register and bit names
- [ ] Map the interrupt vectors vector names
- [ ] Determine what addition registers and bits need to be set, if any
- [ ] Determine if `util/setbaud.h` can still be used
- [ ] If not, sort out how to set the correct baud rate

## References

- [ATmega16M1 Data Sheet](http://www.atmel.com/images/doc8209.pdf) § 20. LIN / UART (pp. 190–213)
- [ATmega2560 Data Sheet](http://www.atmel.com/images/atmel-2549-8-bit-avr-microcontroller-atmega640-1280-1281-2560-2561_datasheet.pdf) § 22. USART (pp. 200–226)
