### ISSUE TITLE
CAN bus communication not implemented

### ISSUE THREAD

**Issue by darrylring** [UVicFormulaMotorsports/CANmon#2]
Right now this is a CAN bus monitor that doesn't know what a CAN bus is. Obviously this is not developed just yet.

## Tasks

- [ ] Determine how the CAN controller needs to be configured
- [ ] Determine how Message Objects (MObs) work
- [ ] Figure out how to receive all CAN frames on a bus
- [ ] Figure out how to filter which CAN frames are received
- [ ] Figure out how to send CAN frames
- [ ] Determine which interrupt vectors need to be used

## References

- [ATmega16M1 Data Sheet](http://www.atmel.com/images/doc8209.pdf) § 19. CAN (pp. 157–189)
- Example: [CAN Example ATmega32M1](https://eewiki.net/display/microcontroller/CAN+Example+-+ATmega32M1+-+STK600)
- Example: [AVR-CAN](https://github.com/OlinREVO/AVR-CAN)
