### ISSUE TITLE
Python package does nothing

### ISSUE THREAD

**Issue by darrylring** [UVicFormulaMotorsports/CANmon#3]
The Python package currently does sweet fuck all.

## Tasks

- [ ] Implement serial communications functions (send commands, read replies and streams)
- [ ] Create a simple CLI
- [ ] Create an interactive CLI
- [ ] Implement saving CAN messages to file, reading messages from file
- [ ] Implement interpreting CAN messages based on a configuration file

## References

- [argparse](https://docs.python.org/3/library/argparse.html) - CLI argument parsing
- [pySerial](http://pyserial.sourceforge.net) - serial communication
- [cmd](https://docs.python.org/3/library/cmd.html) - interactive command interpreter
