### ISSUE TITLE
Hardware design needs review

### ISSUE THREAD

**Issue by darrylring** [UVicFormulaMotorsports/CANmon#4]
The hardware design needs a full review and possibly revision. I designed it in an afternoon.

## Tasks

- [X] Confirm component pinouts
- [X] Ensure nets are connected to correct pins
- [X] Confirm power supplies
- [ ] ~~Possibly revise board layout~~
- [X] Create a shopping cart on Digi-Key

## Resources

- **[Data Sheets](https://github.com/UVicFormulaMotorsports/CANmon/tree/master/hardware/documentation)**
  - ATmega16M1 - Microcontroller
  - FT230X - USB/serial interface
  - SN65HVD230x - CAN transceiver
  - LD1117 - LDO

**Comment by darrylring** [comment]
I went through this quickly. It could probably still use another pair of eyes.
